name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:prod

    - name: Deploy to Github Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@releases/v2
      with:
        TOKEN: ${{ secrets.PISKTOKEN }}
        BRANCH: gh-pages
        FOLDER:  dist/browser

